// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB98O0HYuGye7WDTqOj1Zrg6tnC6Pa2C3o',
    appId: '1:454909722957:web:84b3993527d0919bef3704',
    messagingSenderId: '454909722957',
    projectId: 'todo-app-132184243',
    authDomain: 'todo-app-132184243.firebaseapp.com',
    storageBucket: 'todo-app-132184243.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV4rHBzZWHIB_RGk7ci0vItghxF6PSfhA',
    appId: '1:454909722957:android:9782c568b221dbd6ef3704',
    messagingSenderId: '454909722957',
    projectId: 'todo-app-132184243',
    storageBucket: 'todo-app-132184243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnGv8MViMsIHoIRRzhaM34EAMN5UJDSX4',
    appId: '1:454909722957:ios:f8f5fa97c39f19e2ef3704',
    messagingSenderId: '454909722957',
    projectId: 'todo-app-132184243',
    storageBucket: 'todo-app-132184243.firebasestorage.app',
    iosBundleId: 'com.example.getxExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnGv8MViMsIHoIRRzhaM34EAMN5UJDSX4',
    appId: '1:454909722957:ios:f8f5fa97c39f19e2ef3704',
    messagingSenderId: '454909722957',
    projectId: 'todo-app-132184243',
    storageBucket: 'todo-app-132184243.firebasestorage.app',
    iosBundleId: 'com.example.getxExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB98O0HYuGye7WDTqOj1Zrg6tnC6Pa2C3o',
    appId: '1:454909722957:web:8b92306eddc6d5daef3704',
    messagingSenderId: '454909722957',
    projectId: 'todo-app-132184243',
    authDomain: 'todo-app-132184243.firebaseapp.com',
    storageBucket: 'todo-app-132184243.firebasestorage.app',
  );
}
